name: GitHub Publish NPM package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    env:
      working-directory: ./adr-cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-utl: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - uses: JS-DevTools/npm-publish@v1
        with:
            token: ${{ secrets.NPM_TOKEN }}
            package: ./adr-cli/package.json
