name: GitHub Publish NPM package
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    env:
      working-directory: ./adr-cli
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-utl: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        working-directory: ${{env.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
